name: Bug
description: Report a bug in ddns-go
labels: ['bug']

body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: dropdown
    attributes:
      label: DNS Provider
      description: The DNS provider you are using
      multiple: true
      options:
        - 阿里云
        - 腾讯云
        - DnsPod
        - Cloudflare
        - 华为云
        - Callback
        - 百度云
        - Porkbun
        - GoDaddy
        - Namecheap
        - NameSilo
        - Vercel
        - Dynadot
        - Others

  - type: dropdown
    attributes:
      label: Did you search for similar issues before submitting this one?
      options:
        - No, I didn't
        - Yes, I did, but I didn't find anything useful
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating System
      description: The operating system you are running ddns-go on
      options:
        - Linux
        - Windows
        - macOS (Darwin)
        - FreeBSD
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Architecture
      description: The architecture you are running ddns-go on
      options:
        - i386
        - x86_64
        - armv5
        - armv6
        - armv7
        - arm64
        - mips
        - mipsle
        - mips64
        - mips64le
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: The version of ddns-go you are using
      placeholder: v0.0.1
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How are you running ddns-go?
      options:
        - Docker
        - Service
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any other information
      description: |
        Please provide the steps to reproduce the bug.
        Or any other screenshots or logs that might help us understand the issue better.