name: Feature Request
description: Feature request for ddns-go
labels: ['enhancement']

body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the feature is
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem
      description: Describe the problem you are facing

  - type: textarea
    attributes:
      label: Other Description
      description: Any other information you would like to provide

  - type: checkboxes
    attributes:
      label: Checklist
      description: Please check the following before submitting your feature request
      options:
        - label: I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
          required: true
        - label: I have searched for similar feature requests before submitting this one
          required: true
